title: VkHashDAG Documentation
description: >-
  Ultra-modern documentation for VkHashDAG - GPU-accelerated voxel rendering
  with sophisticated HashDAG implementation and VBR color compression.

baseurl: ""
url: "https://ttxian8.github.io/VkHashDAG"

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 4
  preview_words_before: 8
  preview_words_after: 12
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_sort: order
nav_fold: true

aux_links:
  "GitHub Repository":
    - "https://github.com/ttxian8/VkHashDAG"
  "Issues":
    - "https://github.com/ttxian8/VkHashDAG/issues"

footer_content: "Copyright &copy; 2024 VkHashDAG Project. Distributed under the MIT License."

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ttxian8/VkHashDAG"
gh_edit_branch: "wiki"
gh_edit_view_mode: "edit"

callouts_level: quiet
callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red
  success:
    title: Success
    color: green
  note:
    title: Note
    color: purple

heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

logo: "/assets/images/logo.png"
author: "VkHashDAG Project"
twitter:
  username: vkhashdag
  card: summary_large_image

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: cpp
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build/
  - shader/
  - "*.log"
  - "*.tmp"
